- hosts: localhost
  vars:
    ansible_ssh_private_key_file: "{{ aws_keypair_path }}"
  connection: local
  gather_facts: False

  tasks:

    - name: Provision a set of instances
      ec2:
        instance_type: t2.micro
        group: test
        region: us-east-1
        image: "ami-0f9cf087c1f27d9b1"
        key_name: rbrigden
        wait: true
        count: 1
        state: present
        instance_tags:
          Name: webserver
      register: ec2

    - name: Add all instance public IPs to host group
      add_host: hostname={{ item.public_ip }} groups=ec2hosts
      loop: "{{ ec2.instances }}"

    - name: Wait for ssh to come up
      wait_for: host="{{ item.public_dns_name }}" port=22 delay=10  timeout=300
      with_items: "{{ ec2.instances }}"


- hosts: ec2hosts
  name: provision play
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_private_key_file: "{{ aws_keypair_path }}"
  user: ubuntu
  gather_facts: false

  tasks:
    - name: update
      raw: sudo apt-get -y update

    - name: install python2
      raw: sudo apt-get -y install python python-setuptools

    - name: Install virtualenv
      apt:
        name: virtualenv
        state: present

    - name: Manually create the initial cpstn virtualenv
      command: virtualenv /user/ubuntu/cpstn -p python3 creates="/user/ubuntu/cpstn"

    - pip:
        name:
          - django
        virtualenv: /user/ubuntu/cpstn


